In [ ]:
%pip install pandas
%pip install numpy

In [3]:
import pandas as pd
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [8]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [18]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [19]:
data.dropna(how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [20]:
data[4] = np.nan

In [21]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [22]:
data.dropna(axis="columns", how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [23]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [24]:
df.iloc[:4, 1] = np.nan

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

,0,1,2
0,-0.443437,NaN,NaN
1,0.668962,NaN,NaN
2,0.339183,NaN,1.630229
3,0.265330,NaN,-0.032018
4,1.246463,0.606249,-0.731073
5,-1.676826,0.221085,-0.654338
6,-0.763081,-0.244081,-0.938299


In [27]:
df.dropna()

,0,1,2
4,1.246463,0.606249,-0.731073
5,-1.676826,0.221085,-0.654338
6,-0.763081,-0.244081,-0.938299


In [28]:
df.dropna(thresh=2)

,0,1,2
2,0.339183,NaN,1.630229
3,0.265330,NaN,-0.032018
4,1.246463,0.606249,-0.731073
5,-1.676826,0.221085,-0.654338
6,-0.763081,-0.244081,-0.938299


In [29]:
df.fillna(0)

,0,1,2
0,-0.443437,0.000000,0.000000
1,0.668962,0.000000,0.000000
2,0.339183,0.000000,1.630229
3,0.265330,0.000000,-0.032018
4,1.246463,0.606249,-0.731073
5,-1.676826,0.221085,-0.654338
6,-0.763081,-0.244081,-0.938299


In [30]:
df.fillna({1: 0.5, 2: 0})

,0,1,2
0,-0.443437,0.500000,0.000000
1,0.668962,0.500000,0.000000
2,0.339183,0.500000,1.630229
3,0.265330,0.500000,-0.032018
4,1.246463,0.606249,-0.731073
5,-1.676826,0.221085,-0.654338
6,-0.763081,-0.244081,-0.938299


In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df.iloc[2:, 1] = np.nan

In [33]:
df.iloc[4:, 2] = np.nan

In [34]:
df

,0,1,2
0,-0.733271,-1.154460,0.743878
1,-0.738690,-0.423252,-0.084799
2,0.328739,NaN,0.692033
3,0.728000,NaN,-0.811739
4,-0.689544,NaN,NaN
5,-0.418676,NaN,NaN


In [35]:
df.ffill()

,0,1,2
0,-0.733271,-1.154460,0.743878
1,-0.738690,-0.423252,-0.084799
2,0.328739,-0.423252,0.692033
3,0.728000,-0.423252,-0.811739
4,-0.689544,-0.423252,-0.811739
5,-0.418676,-0.423252,-0.811739


In [36]:
df.ffill(limit=2)

,0,1,2
0,-0.733271,-1.154460,0.743878
1,-0.738690,-0.423252,-0.084799
2,0.328739,-0.423252,0.692033
3,0.728000,-0.423252,-0.811739
4,-0.689544,NaN,-0.811739
5,-0.418676,NaN,-0.811739


In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [39]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [40]:
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [41]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [43]:
data["v1"] = range(7)

In [44]:
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [45]:
data.drop_duplicates(subset=["k1"])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [46]:
data.drop_duplicates(["k1", "k2"], keep="last")

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


In [47]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [48]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [49]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [50]:
data["animal"] = data["food"].map(meat_to_animal)

In [51]:
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


In [52]:
def get_animal(x):
    return meat_to_animal[x]

In [53]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [58]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [61]:
def transform(x):
    return x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [65]:
data.rename(index=str.title, columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [66]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

,one,two,peekaboo,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [67]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [68]:
bins = [18, 25, 35, 60, 100]

In [69]:
age_categories = pd.cut(ages, bins)

In [70]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [71]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [72]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [73]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [74]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [75]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [76]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [77]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [78]:
data = np.random.uniform(size=20)

In [79]:
pd.cut(data, 4, precision=2)

[(0.76, 1.0], (0.058, 0.29], (0.058, 0.29], (0.058, 0.29], (0.058, 0.29], ..., (0.53, 0.76], (0.53, 0.76], (0.53, 0.76], (0.53, 0.76], (0.76, 1.0]]
Length: 20
Categories (4, interval[float64, right]): [(0.058, 0.29] < (0.29, 0.53] < (0.53, 0.76] < (0.76, 1.0]]

In [80]:
data = np.random.standard_normal(1000)

In [81]:
quartiles = pd.qcut(data, 4, precision=2)

In [82]:
quartiles

[(-0.7, 0.032], (-0.7, 0.032], (-0.7, 0.032], (-2.9, -0.7], (-2.9, -0.7], ..., (0.032, 0.73], (0.73, 2.88], (-0.7, 0.032], (0.73, 2.88], (0.73, 2.88]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9, -0.7] < (-0.7, 0.032] < (0.032, 0.73] < (0.73, 2.88]]

In [83]:
quartiles.value_counts()

(-2.9, -0.7]     250
(-0.7, 0.032]    250
(0.032, 0.73]    250
(0.73, 2.88]     250
Name: count, dtype: int64

In [84]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.891, -1.304]    100
(-1.304, 0.0325]    400
(0.0325, 1.374]     400
(1.374, 2.88]       100
Name: count, dtype: int64

In [85]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [86]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.010888,0.006915,-0.049786,-0.009946
std,1.002938,0.953523,0.954842,0.953264
min,-2.945172,-3.253543,-3.320517,-3.330777
25%,-0.641948,-0.619722,-0.699072,-0.645999
50%,0.044748,0.018528,-0.057341,-0.022597
75%,0.677675,0.625226,0.610292,0.611863
max,3.030653,2.825181,2.792426,3.120089


In [87]:
col = data[2]

In [88]:
col[col.abs() > 3]

275   -3.320517
698   -3.010818
Name: 2, dtype: float64

In [89]:
data[(data.abs() > 3).any(axis="columns")]

,0,1,2,3
188,-1.236384,1.980198,0.859615,-3.330777
275,-2.187963,-1.593831,-3.320517,-0.415694
392,-1.683680,-1.476482,1.147282,3.078223
698,0.506653,1.379998,-3.010818,1.062779
765,0.728186,-1.056119,-1.648991,3.120089
951,0.105893,-3.253543,-0.597414,-0.162366
973,3.030653,1.293360,-0.577882,1.320230


In [90]:
data[data.abs() > 3] = np.sign(data) * 3

In [91]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.010857,0.007169,-0.049455,-0.009813
std,1.002846,0.952688,0.953763,0.951529
min,-2.945172,-3.000000,-3.000000,-3.000000
25%,-0.641948,-0.619722,-0.699072,-0.645999
50%,0.044748,0.018528,-0.057341,-0.022597
75%,0.677675,0.625226,0.610292,0.611863
max,3.000000,2.825181,2.792426,3.000000


In [92]:
np.sign(data).head()

,0,1,2,3
0,-1.0,1.0,1.0,-1.0
1,1.0,1.0,1.0,1.0
2,1.0,1.0,-1.0,1.0
3,-1.0,-1.0,-1.0,1.0
4,1.0,1.0,-1.0,-1.0


In [93]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [94]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [95]:
sampler = np.random.permutation(5)

In [96]:
sampler

array([3, 2, 4, 1, 0], dtype=int32)

In [97]:
df.take(sampler)

,0,1,2,3,4,5,6
3,21,22,23,24,25,26,27
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13
0,0,1,2,3,4,5,6


In [98]:
df.iloc[sampler]

,0,1,2,3,4,5,6
3,21,22,23,24,25,26,27
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13
0,0,1,2,3,4,5,6


In [99]:
column_sampler = np.random.permutation(7)

In [100]:
column_sampler

array([4, 0, 1, 6, 2, 3, 5], dtype=int32)

In [101]:
df.take(column_sampler, axis="columns")

,4,0,1,6,2,3,5
0,4,0,1,6,2,3,5
1,11,7,8,13,9,10,12
2,18,14,15,20,16,17,19
3,25,21,22,27,23,24,26
4,32,28,29,34,30,31,33


In [102]:
df.sample(n=3)

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13


In [103]:
choices = pd.Series([5, 7, -1, 6, 4])

In [104]:
choices.sample(n=10, replace=True)

2   -1
1    7
2   -1
0    5
3    6
4    4
1    7
0    5
2   -1
0    5
dtype: int64

In [105]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

In [106]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [107]:
pd.get_dummies(df["key"])

,a,b,c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [108]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [109]:
df_with_dummy = df[["data1"]].join(dummies)

In [110]:
df_with_dummy

,data1,key_a,key_b,key_c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False


In [111]:
mnames = ["movie_id", "title", "genres"]

In [112]:
movies = pd.read_table("../datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

In [113]:
movies[:10]

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [114]:
dummies = movies["genres"].str.get_dummies("|")

In [115]:
dummies.iloc[:10, :6]

,Action,Adventure,Animation,Children's,Comedy,Crime
0,0,0,1,1,1,0
1,0,1,0,1,0,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0
5,1,0,0,0,0,1
6,0,0,0,0,1,0
7,0,1,0,1,0,0
8,1,0,0,0,0,0
9,1,1,0,0,0,0


In [116]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [117]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [118]:
np.random.seed(12345)

In [119]:
values = np.random.uniform(size=10)

In [120]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [121]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [122]:
pd.get_dummies(pd.cut(values, bins))

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,False,False,False,False,True
1,False,True,False,False,False
2,True,False,False,False,False
3,False,True,False,False,False
4,False,False,True,False,False
5,False,False,True,False,False
6,False,False,False,False,True
7,False,False,False,True,False
8,False,False,False,True,False
9,False,False,False,True,False


In [123]:
s = pd.Series([1, 2,  3, None])

In [124]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [125]:
s.dtype

dtype('float64')

In [126]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [127]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [128]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [129]:
s.dtype

Int64Dtype()

In [130]:
s[3]

<NA>

In [131]:
s[3] is pd.NA

True

In [132]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [133]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [134]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [135]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

In [136]:
df

,A,B,C
0,1.0,one,False
1,2.0,two,None
2,NaN,three,False
3,4.0,NaN,True


In [137]:
df["A"] = df["A"].astype("Int64")

In [138]:
df["B"] = df["B"].astype("string")

In [139]:
df["C"] = df["C"].astype("boolean")

In [140]:
df

,A,B,C
0,1,one,False
1,2,two,<NA>
2,<NA>,three,False
3,4,<NA>,True


In [143]:
val = "a,b, guido"

In [144]:
val.split(",")

['a', 'b', ' guido']

In [146]:
pieces = [x.strip() for x in val.split(",")]

In [147]:
pieces

['a', 'b', 'guido']

In [148]:
first, second, third = pieces

In [149]:
first + "::" + second + "::" + third

'a::b::guido'

In [150]:
"::".join(pieces)

'a::b::guido'

In [151]:
"guido" in val

True

In [152]:
val.index(",")

1

In [153]:
val.find(":")

-1

In [154]:
val.index(":")

ValueError: substring not found

In [156]:
val.count(",")

2

In [157]:
val.replace(",", "::")

'a::b:: guido'

In [158]:
val.replace(",", "")

'ab guido'

In [159]:
import re

In [160]:
text = "foo var\t baz \tqux"

In [161]:
re.split(r"\s+", text)

['foo', 'var', 'baz', 'qux']

In [162]:
regax = re.compile(r"\s+")

In [163]:
regax.split(text)

['foo', 'var', 'baz', 'qux']

In [164]:
regax.findall(text)

[' ', '\t ', ' \t']

In [166]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regax = re.compile(pattern, flags=re.IGNORECASE)

In [167]:
regax.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [168]:
m = regax.search(text)

In [169]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [170]:
text[m.start():m.end()]

'dave@google.com'

In [171]:
print(regax.match(text))

None


In [172]:
print(regax.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [177]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [178]:
regax = re.compile(pattern, flags=re.IGNORECASE)

In [179]:
m = regax.match("wesm@bright.net")

In [180]:
m.groups()

('wesm', 'bright', 'net')

In [181]:
regax.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [182]:
print(regax.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [183]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}

In [184]:
data = pd.Series(data)

In [185]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [186]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [187]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [188]:
data_as_string_ext = data.astype('string')

In [189]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [190]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [191]:
pattern = r"([A-Z0-9._%+_]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [192]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [193]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [194]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [195]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [196]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: str

In [197]:
data.str.extract(pattern, flags=re.IGNORECASE)

,0,1,2
Dave,dave,google,com
Steve,steve,gmail,com
Rob,rob,gmail,com
Wes,NaN,NaN,NaN


In [198]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [199]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: str

In [200]:
pd.unique(values)

<ArrowStringArray>
['apple', 'orange']
Length: 2, dtype: str

In [205]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [206]:
values = pd.Series([0, 1, 0, 0] * 2)

In [207]:
dim = pd.Series(['apple', 'orange'])

In [208]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [209]:
dim

0     apple
1    orange
dtype: str

In [210]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: str

In [223]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [224]:
N = len(fruits)

In [225]:
rng  = np.random.default_rng(seed=12345)

In [229]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [230]:
df

,basket_id,fruit,count,weight
0,0,apple,11,2.789814
1,1,orange,11,1.305891
2,2,apple,4,2.935713
3,3,apple,4,0.880540
4,4,apple,6,0.326378
5,5,orange,8,0.639582
6,6,apple,3,1.360401
7,7,apple,13,1.860773


In [231]:
fruit_cat = df['fruit'].astype('category')

In [232]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [233]:
c = fruit_cat.array

In [235]:
type(c)

pandas.Categorical

In [236]:
c.categories

Index(['apple', 'orange'], dtype='str')

In [237]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [238]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [239]:
df['fruit'] = df['fruit'].astype('category')

In [240]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [241]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [242]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, str): ['bar', 'baz', 'foo']

In [243]:
categories = ['foo', 'bar', 'baz']

In [244]:
codes = [0, 1, 2, 0, 0, 1]

In [245]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [246]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo', 'bar', 'baz']

In [247]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)

In [248]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [249]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [250]:
rng = np.random.default_rng(seed=12345)

In [251]:
draws = rng.standard_normal(1000)

In [252]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [253]:
bins = pd.qcut(draws, 4)

In [254]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [255]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [256]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [257]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [258]:
bins = pd.Series(bins, name='quartile')

In [259]:
results = (pd.Series(draws)
            .groupby(bins)
            .agg(['count', 'min', 'max'])
            .reset_index())

In [261]:
results

,quartile,count,min,max
0,Q1,250,-3.119609,-0.678494
1,Q2,250,-0.673305,0.008009
2,Q3,250,0.018753,0.686183
3,Q4,250,0.688282,3.211418


In [262]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [263]:
N = 10_000_000

In [264]:
labels = pd.Series(['foo', 'bar', 'baz', 'quz'] * (N // 4))

In [265]:
categories = labels.astype('category')

In [266]:
labels.memory_usage(deep=True)

110000132

In [267]:
categories.memory_usage(deep=True)

10000177

In [268]:
%time _ = labels.astype('category')

CPU times: total: 359 ms
Wall time: 354 ms


In [269]:
%timeit labels.value_counts()

118 ms ± 3.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [270]:
%timeit categories.value_counts()

52 ms ± 12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [271]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [272]:
cat_s = s.astype('category')

In [273]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [274]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [275]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='str')

In [276]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [277]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [278]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [279]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [280]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [281]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [282]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [283]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']

In [284]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [285]:
pd.get_dummies(cat_s)

,a,b,c,d
0,True,False,False,False
1,False,True,False,False
2,False,False,True,False
3,False,False,False,True
4,True,False,False,False
5,False,True,False,False
6,False,False,True,False
7,False,False,False,True
