In [ ]:
%pip install pandas
%pip install numpy

In [3]:
import pandas as pd
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [8]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [18]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [19]:
data.dropna(how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [20]:
data[4] = np.nan

In [21]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [22]:
data.dropna(axis="columns", how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [23]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [24]:
df.iloc[:4, 1] = np.nan

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

,0,1,2
0,-0.505934,NaN,NaN
1,0.198814,NaN,NaN
2,-0.080999,NaN,-0.048541
3,0.182730,NaN,-0.982726
4,1.545513,0.419627,-0.725407
5,0.816117,0.010783,-0.731892
6,1.268482,-0.513455,0.810688


In [27]:
df.dropna()

,0,1,2
4,1.545513,0.419627,-0.725407
5,0.816117,0.010783,-0.731892
6,1.268482,-0.513455,0.810688


In [28]:
df.dropna(thresh=2)

,0,1,2
2,-0.080999,NaN,-0.048541
3,0.182730,NaN,-0.982726
4,1.545513,0.419627,-0.725407
5,0.816117,0.010783,-0.731892
6,1.268482,-0.513455,0.810688


In [29]:
df.fillna(0)

,0,1,2
0,-0.505934,0.000000,0.000000
1,0.198814,0.000000,0.000000
2,-0.080999,0.000000,-0.048541
3,0.182730,0.000000,-0.982726
4,1.545513,0.419627,-0.725407
5,0.816117,0.010783,-0.731892
6,1.268482,-0.513455,0.810688


In [30]:
df.fillna({1: 0.5, 2: 0})

,0,1,2
0,-0.505934,0.500000,0.000000
1,0.198814,0.500000,0.000000
2,-0.080999,0.500000,-0.048541
3,0.182730,0.500000,-0.982726
4,1.545513,0.419627,-0.725407
5,0.816117,0.010783,-0.731892
6,1.268482,-0.513455,0.810688


In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df.iloc[2:, 1] = np.nan

In [33]:
df.iloc[4:, 2] = np.nan

In [34]:
df

,0,1,2
0,2.124012,0.631478,-0.694360
1,0.250020,0.144334,0.359617
2,-1.000299,NaN,0.130500
3,0.912332,NaN,0.736255
4,-0.119231,NaN,NaN
5,-1.787145,NaN,NaN


In [35]:
df.ffill()

,0,1,2
0,2.124012,0.631478,-0.694360
1,0.250020,0.144334,0.359617
2,-1.000299,0.144334,0.130500
3,0.912332,0.144334,0.736255
4,-0.119231,0.144334,0.736255
5,-1.787145,0.144334,0.736255


In [36]:
df.ffill(limit=2)

,0,1,2
0,2.124012,0.631478,-0.694360
1,0.250020,0.144334,0.359617
2,-1.000299,0.144334,0.130500
3,0.912332,0.144334,0.736255
4,-0.119231,NaN,0.736255
5,-1.787145,NaN,0.736255


In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [39]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [40]:
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [41]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [43]:
data["v1"] = range(7)

In [44]:
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [45]:
data.drop_duplicates(subset=["k1"])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [46]:
data.drop_duplicates(["k1", "k2"], keep="last")

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


In [47]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [48]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [49]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [50]:
data["animal"] = data["food"].map(meat_to_animal)

In [51]:
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


In [52]:
def get_animal(x):
    return meat_to_animal[x]

In [53]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [58]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [61]:
def transform(x):
    return x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [65]:
data.rename(index=str.title, columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [66]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

,one,two,peekaboo,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [67]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [68]:
bins = [18, 25, 35, 60, 100]

In [69]:
age_categories = pd.cut(ages, bins)

In [70]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [71]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [72]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [73]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [76]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [77]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [78]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [79]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [80]:
data = np.random.uniform(size=20)

In [81]:
pd.cut(data, 4, precision=2)

[(0.49, 0.69], (0.69, 0.9], (0.49, 0.69], (0.29, 0.49], (0.29, 0.49], ..., (0.69, 0.9], (0.29, 0.49], (0.49, 0.69], (0.29, 0.49], (0.29, 0.49]]
Length: 20
Categories (4, interval[float64, right]): [(0.082, 0.29] < (0.29, 0.49] < (0.49, 0.69] < (0.69, 0.9]]

In [82]:
data = np.random.standard_normal(1000)

In [83]:
quartiles = pd.qcut(data, 4, precision=2)

In [84]:
quartiles

[(0.75, 3.19], (0.034, 0.75], (0.034, 0.75], (-0.71, 0.034], (0.75, 3.19], ..., (-3.36, -0.71], (0.034, 0.75], (0.034, 0.75], (0.034, 0.75], (0.034, 0.75]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.36, -0.71] < (-0.71, 0.034] < (0.034, 0.75] < (0.75, 3.19]]

In [86]:
quartiles.value_counts()

(-3.36, -0.71]    250
(-0.71, 0.034]    250
(0.034, 0.75]     250
(0.75, 3.19]      250
Name: count, dtype: int64

In [87]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.352, -1.341]    100
(-1.341, 0.0339]    400
(0.0339, 1.354]     400
(1.354, 3.187]      100
Name: count, dtype: int64

In [88]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [90]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.080044,0.009095,0.012113,0.056263
std,0.924968,0.949415,0.990153,1.013996
min,-3.505666,-2.955563,-3.369774,-3.342373
25%,-0.534857,-0.617785,-0.662063,-0.613650
50%,0.042856,0.014531,0.065263,0.042828
75%,0.696122,0.612211,0.676144,0.761125
max,2.892742,2.795446,2.846473,2.785841


In [91]:
col = data[2]

In [92]:
col[col.abs() > 3]

287   -3.369774
Name: 2, dtype: float64

In [93]:
data[(data.abs() > 3).any(axis="columns")]

,0,1,2,3
51,-3.505666,0.636587,0.199205,-1.763586
83,-0.896364,-0.452285,-0.479690,-3.102255
287,-0.264563,0.215744,-3.369774,-0.097266
300,-0.194157,-0.287555,-0.346009,-3.133324
609,0.219889,-0.364779,0.577844,-3.169617
646,-0.361855,1.149151,-0.115634,-3.342373


In [94]:
data[data.abs() > 3] = np.sign(data) * 3

In [95]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.080550,0.009095,0.012483,0.057011
std,0.923142,0.949415,0.988957,1.011652
min,-3.000000,-2.955563,-3.000000,-3.000000
25%,-0.534857,-0.617785,-0.662063,-0.613650
50%,0.042856,0.014531,0.065263,0.042828
75%,0.696122,0.612211,0.676144,0.761125
max,2.892742,2.795446,2.846473,2.785841


In [97]:
np.sign(data).head()

,0,1,2,3
0,-1.0,1.0,-1.0,1.0
1,1.0,-1.0,-1.0,1.0
2,1.0,1.0,-1.0,-1.0
3,1.0,1.0,1.0,1.0
4,1.0,1.0,1.0,-1.0


In [98]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [99]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [100]:
sampler = np.random.permutation(5)

In [101]:
sampler

array([0, 2, 4, 3, 1], dtype=int32)

In [102]:
df.take(sampler)

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
1,7,8,9,10,11,12,13


In [104]:
df.iloc[sampler]

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
1,7,8,9,10,11,12,13


In [105]:
column_sampler = np.random.permutation(7)

In [106]:
column_sampler

array([1, 2, 3, 6, 4, 0, 5], dtype=int32)

In [107]:
df.take(column_sampler, axis="columns")

,1,2,3,6,4,0,5
0,1,2,3,6,4,0,5
1,8,9,10,13,11,7,12
2,15,16,17,20,18,14,19
3,22,23,24,27,25,21,26
4,29,30,31,34,32,28,33


In [110]:
df.sample(n=3)

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27


In [111]:
choices = pd.Series([5, 7, -1, 6, 4])

In [112]:
choices.sample(n=10, replace=True)

1    7
3    6
2   -1
1    7
3    6
2   -1
0    5
0    5
0    5
0    5
dtype: int64

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [115]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

In [116]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [117]:
pd.get_dummies(df["key"])

,a,b,c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [118]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [119]:
df_with_dummy = df[["data1"]].join(dummies)

In [121]:
df_with_dummy

,data1,key_a,key_b,key_c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False


In [122]:
mnames = ["movie_id", "title", "genres"]

In [123]:
movies = pd.read_table("../datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

In [124]:
movies[:10]

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [125]:
dummies = movies["genres"].str.get_dummies("|")

In [126]:
dummies.iloc[:10, :6]

,Action,Adventure,Animation,Children's,Comedy,Crime
0,0,0,1,1,1,0
1,0,1,0,1,0,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0
5,1,0,0,0,0,1
6,0,0,0,0,1,0
7,0,1,0,1,0,0
8,1,0,0,0,0,0
9,1,1,0,0,0,0


In [127]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [128]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [129]:
np.random.seed(12345)

In [130]:
values = np.random.uniform(size=10)

In [131]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [132]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [133]:
pd.get_dummies(pd.cut(values, bins))

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,False,False,False,False,True
1,False,True,False,False,False
2,True,False,False,False,False
3,False,True,False,False,False
4,False,False,True,False,False
5,False,False,True,False,False
6,False,False,False,False,True
7,False,False,False,True,False
8,False,False,False,True,False
9,False,False,False,True,False


In [134]:
s = pd.Series([1, 2,  3, None])

In [135]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [136]:
s.dtype

dtype('float64')

In [137]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [138]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [139]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [140]:
s.dtype

Int64Dtype()

In [141]:
s[3]

<NA>

In [142]:
s[3] is pd.NA

True

In [144]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [145]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [146]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [147]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

In [148]:
df

,A,B,C
0,1.0,one,False
1,2.0,two,None
2,NaN,three,False
3,4.0,NaN,True


In [150]:
df["A"] = df["A"].astype("Int64")

In [152]:
df["B"] = df["B"].astype("string")

In [155]:
df["C"] = df["C"].astype("boolean")

In [156]:
df

,A,B,C
0,1,one,False
1,2,two,<NA>
2,<NA>,three,False
3,4,<NA>,True
