In [1]:
import numpy as np

In [ ]:
%pip install pandas

In [3]:
import pandas as pd

In [4]:
from pandas import Series, DataFrame

In [5]:
obj = pd.Series([4, 7, -5, 3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

In [12]:
obj2["a"]

np.int64(-5)

In [13]:
obj2["d"] = 6

In [14]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
import numpy as np

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
"b" in obj2

True

In [20]:
"e" in obj2

False

In [21]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [25]:
states = ["Colifronia", "Ohio", "Oregon", "Texas"]

In [26]:
obj4 = pd.Series(sdata, index=states)

In [27]:
obj4

Colifronia        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isna(obj4)

Colifronia     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notna(obj4)

Colifronia    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

Colifronia        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3 + obj4

Colifronia         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = "population"

In [34]:
obj4.index.name = "state"

In [35]:
obj4

state
Colifronia        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [38]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [39]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002,  2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [40]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [41]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [42]:
frame.tail()

,state,year,pop
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [43]:
pd.DataFrame(data, columns=["year", "state", "pop"])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [44]:
frame2 = pd.DataFrame(data,  columns=["year", "state", "pop", "debt"])

In [45]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [47]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [48]:
frame2.year                                               

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [49]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [50]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [51]:
frame2["debt"] = 16.5

In [52]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,16.5
1,2001,Ohio,1.7,16.5
2,2002,Ohio,3.6,16.5
3,2001,Nevada,2.4,16.5
4,2002,Nevada,2.9,16.5
5,2003,Nevada,3.2,16.5


In [53]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,16.5
1,2001,Ohio,1.7,16.5
2,2002,Ohio,3.6,16.5
3,2001,Nevada,2.4,16.5
4,2002,Nevada,2.9,16.5
5,2003,Nevada,3.2,16.5


In [54]:
frame2["debt"] = np.arange(6.)

In [55]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,0.0
1,2001,Ohio,1.7,1.0
2,2002,Ohio,3.6,2.0
3,2001,Nevada,2.4,3.0
4,2002,Nevada,2.9,4.0
5,2003,Nevada,3.2,5.0


In [56]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [57]:
frame2["debt"] = val

In [58]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [59]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [60]:
frame2

,year,state,pop,debt,eastern
0,2000,Ohio,1.5,NaN,True
1,2001,Ohio,1.7,NaN,True
2,2002,Ohio,3.6,NaN,True
3,2001,Nevada,2.4,NaN,False
4,2002,Nevada,2.9,NaN,False
5,2003,Nevada,3.2,NaN,False


In [61]:
del frame2["eastern"]

In [62]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [63]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [64]:
frame3 = pd.DataFrame(populations)

In [65]:
frame3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [66]:
frame3.T

,2000,2001,2002
Ohio,1.5,1.7,3.6
Nevada,NaN,2.4,2.9


In [67]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9
2003,NaN,NaN


In [68]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}

In [69]:
pd.DataFrame(pdata)

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4


In [70]:
frame3.index.name = "year"

In [71]:
frame3.columns.name = "state"

In [72]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [73]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [74]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [75]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [76]:
index = obj.index

In [77]:
index


Index(['a', 'b', 'c'], dtype='str')

In [78]:
index[1:]

Index(['b', 'c'], dtype='str')

In [ ]:
index[1] = "d"

In [80]:
labels = pd.Index(np.arange(3))

In [81]:
labels

Index([0, 1, 2], dtype='int64')

In [82]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [83]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [84]:
obj2.index is labels

True

In [85]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [86]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='str', name='state')

In [87]:
"Ohio" in frame3.columns

True

In [88]:
2003 in frame3.index

False

In [89]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [90]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [91]:
obj


d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [92]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [93]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [94]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [95]:
obj3

0      blue
2    purple
4    yellow
dtype: str

In [96]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [97]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=["a", "c", "d"],
                    columns=["Ohio", "Texas", "California"])

In [98]:
frame

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [99]:
frame2 = frame.reindex(index=["a","b", "c", "d"])

In [100]:
frame2

,Ohio,Texas,California
a,0.0,1.0,2.0
b,NaN,NaN,NaN
c,3.0,4.0,5.0
d,6.0,7.0,8.0


In [101]:
states = ["Texas", "Utah", "California"]

In [102]:
frame.reindex(columns=states)

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [103]:
frame.reindex(states, axis="columns")

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [104]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

,California,Texas
a,2,1
d,8,7
c,5,4


In [105]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [106]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [107]:
new_obj = obj.drop("c")

In [108]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [109]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [110]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

In [111]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [112]:
data.drop(index=["Colorado", "Ohio"])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [113]:
data.drop(columns=["two"])

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [114]:
data.drop("two", axis=1)

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [115]:
data.drop(["two", "four"], axis="columns")

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [116]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [117]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [118]:
obj["b"]

np.float64(1.0)

In [119]:
obj.iloc[1]

np.float64(1.0)

In [120]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [121]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [122]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [123]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [124]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [125]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [126]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [127]:
obj1

2    1
0    2
1    3
dtype: int64

In [128]:
obj2

a    1
b    2
c    3
dtype: int64

In [129]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [130]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [131]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [132]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [133]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [134]:
obj2.loc["b":"c"] = 5

In [135]:
obj2

a    1
b    5
c    5
dtype: int64

In [136]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two",  "three", "four"])

In [137]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [138]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [139]:
data[["three", "one"]]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [140]:
data[:2]

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7


In [141]:
data[data["three"] > 5]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [142]:
data < 5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [143]:
data[data < 5] = 0

In [144]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [145]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [146]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [147]:
data.loc[["Colorado", "New York"]]

,one,two,three,four
Colorado,0,5,6,7
New York,12,13,14,15


In [148]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [149]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [150]:
data.iloc[[2, 1]]

,one,two,three,four
Utah,8,9,10,11
Colorado,0,5,6,7


In [151]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [152]:
data.iloc[[1, 2], [3, 0, 1]]

,four,one,two
Colorado,7,0,5
Utah,11,8,9


In [153]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [154]:
data.iloc[:, :3][data.three > 5]

,one,two,three
Colorado,0,5,6
Utah,8,9,10
New York,12,13,14


In [155]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [156]:
ser = pd.Series(np.arange(3.))

In [157]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser[-1]

In [159]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [ ]:
ser2[-1]

In [161]:
ser.iloc[-1]

np.float64(2.0)

In [162]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [163]:
data.loc[:, "one"] = 1

In [164]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,1,9,10,11
New York,1,13,14,15


In [165]:
data.iloc[2] = 5

In [166]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,5,5,5,5
New York,1,13,14,15


In [167]:
data.loc[data["four"] > 5] = 3

In [168]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [ ]:
data.loc[data.three == 5]["three"] = 6

In [170]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [171]:
data.loc[data.three == 5, "three"] = 6

In [172]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,6,5
New York,3,3,3,3


In [173]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [174]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
                index=["a", "c", "e", "f", "g"])

In [175]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [176]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [177]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [178]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

In [179]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

In [180]:
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [181]:
df2

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [182]:
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


In [183]:
df1 = pd.DataFrame({"A": [1, 2]})

In [184]:
df2 = pd.DataFrame({"B": [3, 4]})

In [185]:
df1

,A
0,1
1,2


In [186]:
df2

,B
0,3
1,4


In [187]:
df1 + df2

,A,B
0,NaN,NaN
1,NaN,NaN


In [188]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))

In [189]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

In [190]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [191]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [192]:
df2.loc[1, "b"] = np.nan

In [193]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [194]:
df1 + df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [195]:
df1.add(df2, fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [196]:
1 / df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [197]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [198]:
df1.rdiv(1)

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [199]:
df1.reindex(columns=df2.columns, fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [200]:
arr = np.arange(12.).reshape((3, 4))

In [201]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [202]:
arr[0]

array([0., 1., 2., 3.])

In [203]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [204]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])

In [205]:
series = frame.iloc[0]

In [206]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [207]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [208]:
frame - series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


In [209]:
series2 = pd.Series(np.arange(3), index=["b","e", "f"])

In [210]:
series2

b    0
e    1
f    2
dtype: int64

In [211]:
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [212]:
series3 = frame["d"]

In [213]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [214]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [215]:
frame.sub(series3, axis="index")

,b,d,e
Utah,-1.0,0.0,1.0
Ohio,-1.0,0.0,1.0
Texas,-1.0,0.0,1.0
Oregon,-1.0,0.0,1.0


In [216]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])

In [217]:
frame

,b,d,e
Utah,-1.662488,-2.137432,1.237812
Ohio,1.063208,-0.508032,-0.304198
Texas,1.429018,1.527491,0.229969
Oregon,0.961949,1.390205,-1.248865


In [218]:
np.abs(frame)

,b,d,e
Utah,1.662488,2.137432,1.237812
Ohio,1.063208,0.508032,0.304198
Texas,1.429018,1.527491,0.229969
Oregon,0.961949,1.390205,1.248865


In [219]:
def f1(x):
    return x.max() - x.min()

In [220]:
frame.apply(f1)

b    3.091507
d    3.664923
e    2.486677
dtype: float64

In [221]:
frame.apply(f1, axis="columns")

Utah      3.375244
Ohio      1.571239
Texas     1.297523
Oregon    2.639070
dtype: float64

In [222]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [223]:
frame.apply(f2)

,b,d,e
min,-1.662488,-2.137432,-1.248865
max,1.429018,1.527491,1.237812


In [224]:
def my_format(x):
    return f"{x:.2f}"

In [225]:
frame.map(my_format)

,b,d,e
Utah,-1.66,-2.14,1.24
Ohio,1.06,-0.51,-0.30
Texas,1.43,1.53,0.23
Oregon,0.96,1.39,-1.25


In [226]:
frame["e"].map(my_format)

Utah       1.24
Ohio      -0.30
Texas      0.23
Oregon    -1.25
Name: e, dtype: str

In [228]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [229]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [230]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [231]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=["three", "one"],
                    columns=["d", "a", "b", "c"])

In [232]:
frame

,d,a,b,c
three,0,1,2,3
one,4,5,6,7


In [233]:
frame.sort_index()

,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [234]:
frame.sort_index(axis="columns")

,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [235]:
frame.sort_index(axis="columns", ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [236]:
obj = pd.Series([4, 7, -3, 2])

In [237]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [238]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [239]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [240]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [241]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [242]:
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [244]:
frame.sort_values("b")

,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [245]:
frame.sort_values(["a", "b"])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [246]:
obj = pd.Series([7, -5, 7, 5, 2, 0, 4])

In [247]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    5.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [248]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [249]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [250]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [251]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
        "c": [-2, 5, 8, -2.5]})


In [252]:
frame

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [253]:
frame.rank(axis="columns")

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [254]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [255]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [256]:
obj.index.is_unique

False

In [257]:
obj["a"]

a    0
a    1
dtype: int64

In [258]:
obj["c"]

np.int64(4)

In [259]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a",  "b", "b", "c"])

In [260]:
df

,0,1,2
a,0.482283,-1.855070,-0.081453
a,-0.026401,-0.383866,0.225887
b,-0.372347,0.267104,0.503994
b,-0.684896,0.060792,1.592649
c,-0.474937,-0.038344,-1.364867


In [261]:
df.loc["b"]

,0,1,2
b,-0.372347,0.267104,0.503994
b,-0.684896,0.060792,1.592649


In [262]:
df.loc["c"]

0   -0.474937
1   -0.038344
2   -1.364867
Name: c, dtype: float64

In [263]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index=["a", "b", "c", "d"],
                   columns=["one", "two"])

In [264]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [265]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [266]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [267]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [269]:
df.sum(axis=0, skipna=False)

one   NaN
two   NaN
dtype: float64

In [270]:
df.sum(axis=1, skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [271]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [273]:
df.idxmax()

one    b
two    d
dtype: str

In [274]:
df.cumsum()

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [275]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [276]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [277]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: str

In [279]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [ ]:
pip install yfinance

In [289]:
import yfinance as yf

tickers = ['AAPL', 'GOOG', 'MSFT', 'AMZN', 'IBM']

# Загружаем данные по акциям за нужный период
data = yf.download(tickers, start='2024-01-01', end='2026-01-01')

# Извлекаем цены закрытия и объёмы торгов:
price = data['Close']
volume = data['Volume']

[*********************100%***********************]  5 of 5 completed


In [290]:
returns = price.pct_change()

In [291]:
returns.tail()

Ticker,AAPL,AMZN,GOOG,IBM,MSFT
Date,,,,,
2025-12-24,0.005324,0.001034,-0.000032,0.002568,0.002403
2025-12-26,-0.001497,0.000602,-0.002249,0.001740,-0.000635
2025-12-29,0.001317,-0.001935,-0.001810,0.002131,-0.001251
2025-12-30,-0.002484,0.001982,0.000509,-0.012069,0.000780
2025-12-31,-0.004467,-0.007354,-0.002384,-0.019335,-0.007918


In [292]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.1766482872953296)

In [294]:
returns["MSFT"].cov(returns["IBM"])

np.float64(4.1924860414187733e-05)

In [295]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.1766482872953296)

In [296]:
returns.corr()

Ticker,AAPL,AMZN,GOOG,IBM,MSFT
Ticker,,,,,
AAPL,1.000000,0.484033,0.446279,0.271708,0.479061
AMZN,0.484033,1.000000,0.536527,0.225823,0.625640
GOOG,0.446279,0.536527,1.000000,0.232369,0.487259
IBM,0.271708,0.225823,0.232369,1.000000,0.176648
MSFT,0.479061,0.625640,0.487259,0.176648,1.000000


In [297]:
returns.cov()

Ticker,AAPL,AMZN,GOOG,IBM,MSFT
Ticker,,,,,
AAPL,0.000309,0.000168,0.000148,0.000081,0.000118
AMZN,0.000168,0.000391,0.000200,0.000076,0.000173
GOOG,0.000148,0.000200,0.000354,0.000074,0.000128
IBM,0.000081,0.000076,0.000074,0.000288,0.000042
MSFT,0.000118,0.000173,0.000128,0.000042,0.000195


In [298]:
returns.corrwith(returns["IBM"])

Ticker
AAPL    0.271708
AMZN    0.225823
GOOG    0.232369
IBM     1.000000
MSFT    0.176648
dtype: float64

In [299]:
returns.corrwith(volume)

Ticker
AAPL    0.089719
AMZN    0.023450
GOOG    0.067017
IBM     0.073242
MSFT   -0.086283
dtype: float64

In [300]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [303]:
uniques = obj.unique()

In [304]:
uniques

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [306]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [311]:
obj.value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [312]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [313]:
mask = obj.isin(["b", "c"])

In [314]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [316]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: str

In [317]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [318]:
unique_vals = pd.Series(["c", "b", "a"])

In [319]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [320]:
indices

array([0, 2, 1, 1, 0, 2])

In [323]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Que2": [2, 3, 1, 2, 3],
                     "Que3": [1, 5, 2, 4, 4]})

In [324]:
data

,Qu1,Que2,Que3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [325]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [ ]:
result = data.apply(pd.Series.value_counts).fillna(0)

In [328]:
result

,Qu1,Que2,Que3
1,1.0,1.0,1.0
2,0.0,2.0,1.0
3,2.0,2.0,0.0
4,2.0,0.0,2.0
5,0.0,0.0,1.0


In [329]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2,], "b": [0, 0, 1, 0, 0]})

In [330]:
data

,a,b
0,1,0
1,1,0
2,1,1
3,2,0
4,2,0


In [331]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64